services:
  db:
    ports: !reset []

  redis:
    ports: !reset []

  auth-service:
    ports: !reset []

  user-service:
    ports: !reset []

  notification-service:
    ports: !reset []

  project-service:
    ports: !reset []

  etcd:
    ports: !reset []

  apisix:
    ports: !override
      - "127.0.0.1:${APISIX_NODE_LISTEN:-9080}:${APISIX_NODE_LISTEN:-9080}"

  apisix-homepage:
    ports: !reset []
