export const RAW_USERS = [
  {
    id: 'ln',
    name: 'leonel.ngoya',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=ln',
    email: 'leonelngoya@gmail.com',
    status: 'online',
    role: 'Admin',
    joinedDate: '2022-01-01',
    timezone: 'Europe/Paris',
    teamIds: ['CORE', 'PERF', 'DESIGN', 'WEB'],
  },
  {
    id: 'sophia',
    name: 'sophia.reed',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=sophiareed',
    email: 'sophiareed@gmail.com',
    status: 'offline',
    role: 'Admin',
    joinedDate: '2023-06-04',
    timezone: 'America/New_York',
    teamIds: ['CORE', 'PERF'],
  },
  {
    id: 'mason',
    name: 'mason.carter',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=mason',
    email: 'masoncarter@gmail.com',
    status: 'away',
    role: 'Member',
    joinedDate: '2023-11-01',
    timezone: 'Europe/London',
    teamIds: ['CORE', 'DESIGN'],
  },
  {
    id: 'emma',
    name: 'emma.jones',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=emmajones',
    email: 'emmajones@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2023-03-20',
    timezone: 'Asia/Tokyo',
    teamIds: ['CORE'],
  },
  {
    id: 'alex',
    name: 'alex.zhang',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=alexzhang',
    email: 'alexzhang@gmail.com',
    status: 'online',
    role: 'Member',
    joinedDate: '2023-05-15',
    timezone: 'America/Los_Angeles',
    teamIds: ['DESIGN', 'PERF'],
  },
  {
    id: 'olivia',
    name: 'olivia.wilson',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=oliviawilson',
    email: 'oliviawilson@gmail.com',
    status: 'offline',
    role: 'Admin',
    joinedDate: '2022-08-22',
    timezone: 'Europe/Berlin',
    teamIds: ['PERF'],
  },
  {
    id: 'lucas',
    name: 'lucas.martin',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=lucasmartin',
    email: 'lucasmartin@gmail.com',
    status: 'away',
    role: 'Member',
    joinedDate: '2023-02-14',
    timezone: 'America/Sao_Paulo',
    teamIds: ['CORE', 'DESIGN', 'PERF'],
  },
  {
    id: 'isabella',
    name: 'isabella.garcia',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=isabellagarcia',
    email: 'isabellagarcia@gmail.com',
    status: 'online',
    role: 'Member',
    joinedDate: '2022-11-30',
    timezone: 'Asia/Singapore',
    teamIds: ['DESIGN'],
  },
  {
    id: 'ethan',
    name: 'ethan.brown',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=ethanbrown',
    email: 'ethanbrown@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2023-07-18',
    timezone: 'Europe/Madrid',
    teamIds: ['PERF'],
  },
  {
    id: 'amelia',
    name: 'amelia.kim',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=ameliakim',
    email: 'ameliakim@gmail.com',
    status: 'offline',
    role: 'Guest',
    joinedDate: '2022-05-09',
    timezone: 'Africa/Douala',
    teamIds: ['DESIGN'],
  },
  {
    id: 'noah',
    name: 'noah.davis',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=noahdavis',
    email: 'noahdavis@gmail.com',
    status: 'away',
    role: 'Member',
    joinedDate: '2023-09-27',
    timezone: 'America/Chicago',
    teamIds: ['PERF', 'DESIGN'],
  },
  {
    id: 'charlotte',
    name: 'charlotte.miller',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=charlottemiller',
    email: 'charlottemiller@gmail.com',
    status: 'offline',
    role: 'Guest',
    joinedDate: '2022-04-03',
    timezone: 'Europe/Amsterdam',
    teamIds: ['PERF'],
  },
  {
    id: 'aiden',
    name: 'aiden.thompson',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=aidenthompson',
    email: 'aidenthompson@gmail.com',
    status: 'offline',
    role: 'Admin',
    joinedDate: '2023-01-12',
    timezone: 'Asia/Dubai',
    teamIds: ['DESIGN'],
  },
  {
    id: 'mia',
    name: 'mia.patel',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=miapatel',
    email: 'miapatel@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2022-10-05',
    timezone: 'Europe/Lisbon',
    teamIds: ['DESIGN', 'PERF'],
  },
  {
    id: 'logan',
    name: 'logan.wright',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=loganwright',
    email: 'loganwright@gmail.com',
    status: 'away',
    role: 'Guest',
    joinedDate: '2023-08-14',
    timezone: 'America/Toronto',
    teamIds: ['PERF', 'DESIGN'],
  },
  {
    id: 'harper',
    name: 'harper.robinson',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=harperrobinson',
    email: 'harperrobinson@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2022-07-29',
    timezone: 'Europe/Stockholm',
    teamIds: ['PERF'],
  },
  {
    id: 'gabriel',
    name: 'gabriel.nguyen',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=gabrielnguyen',
    email: 'gabrielnguyen@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2023-04-17',
    timezone: 'Asia/Seoul',
    teamIds: ['DESIGN'],
  },
  {
    id: 'victoria',
    name: 'victoria.lee',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=victorialee',
    email: 'victorialee@gmail.com',
    status: 'away',
    role: 'Guest',
    joinedDate: '2022-12-08',
    timezone: 'Europe/Zurich',
    teamIds: ['DESIGN'],
  },
  {
    id: 'daniel',
    name: 'daniel.taylor',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=danieltaylor',
    email: 'danieltaylor@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2023-10-21',
    timezone: 'America/Denver',
    teamIds: ['PERF'],
  },
  {
    id: 'abigail',
    name: 'abigail.moore',
    avatarUrl: 'https://api.dicebear.com/9.x/glass/svg?seed=abigailmoore',
    email: 'abigailmoore@gmail.com',
    status: 'offline',
    role: 'Member',
    joinedDate: '2022-06-17',
    timezone: 'Europe/Dublin',
    teamIds: ['DESIGN', 'PERF'],
  },
  {
    id: 'atlas',
    name: 'atlas',
    avatarUrl: 'https://api.dicebear.com/9.x/bottts/svg?seed=atlasagent',
    email: 'atlas@lndev-ui.dev',
    status: 'offline',
    role: 'Application',
    joinedDate: '2026-01-08',
    timezone: 'UTC',
    teamIds: [],
  },
  {
    id: 'nova',
    name: 'nova',
    avatarUrl: 'https://api.dicebear.com/9.x/bottts/svg?seed=novaagent',
    email: 'nova@lndev-ui.dev',
    status: 'offline',
    role: 'Application',
    joinedDate: '2026-01-15',
    timezone: 'UTC',
    teamIds: ['CORE', 'WEB', 'PERF', 'DESIGN', 'MOBILE', 'UI'],
  },
];

export const RAW_TEAMS = [
  { id: 'CORE', name: 'LNDev Core', icon: '🛠️', joined: true, color: '#FF0000' },
  { id: 'DESIGN', name: 'Design System', icon: '🎨', joined: true, color: '#00FF00' },
  { id: 'PERF', name: 'Performance Lab', icon: '☀️', joined: false, color: '#0000FF' },
  { id: 'UX', name: 'UX Team', icon: '👨🏼‍🎨', joined: false, color: '#FF00FF' },
  { id: 'DATA', name: 'Data Science', icon: '📊', joined: false, color: '#0000FF' },
  { id: 'MOBILE', name: 'Mobile Development', icon: '📱', joined: false, color: '#0000FF' },
  { id: 'WEB', name: 'Web Development', icon: '🌐', joined: true, color: '#0000FF' },
  { id: 'UI', name: 'UI Team', icon: '👨🏼‍🎨', joined: false, color: '#FF00FF' },
  { id: 'CLOUD', name: 'Cloud Infrastructure', icon: '☁️', joined: false, color: '#4A90E2' },
  { id: 'SECURITY', name: 'Security Team', icon: '🔒', joined: false, color: '#2E2E2E' },
  { id: 'AI', name: 'AI Research', icon: '🧠', joined: true, color: '#9B59B6' },
  { id: 'QA', name: 'Quality Assurance', icon: '✅', joined: false, color: '#F1C40F' },
  { id: 'DEVOPS', name: 'DevOps', icon: '⚙️', joined: false, color: '#E67E22' },
  { id: 'FRONTEND', name: 'Frontend Experts', icon: '🖥️', joined: false, color: '#1ABC9C' },
  { id: 'BACKEND', name: 'Backend Engineers', icon: '🗄️', joined: false, color: '#34495E' },
  { id: 'PRODUCT', name: 'Product', icon: '📋', joined: false, color: '#C0392B' },
  { id: 'ANALYTICS', name: 'Analytics Team', icon: '📈', joined: false, color: '#7F8C8D' },
  { id: 'INNO', name: 'Innovation Lab', icon: '💡', joined: false, color: '#F39C12' },
  { id: 'API', name: 'API Development', icon: '🔌', joined: false, color: '#16A085' },
  { id: 'UXR', name: 'UX Research', icon: '🔍', joined: false, color: '#8E44AD' },
];

export const RAW_LABELS = [
  { id: 'ui', name: 'UI Enhancement', color: 'purple' },
  { id: 'bug', name: 'Bug', color: 'red' },
  { id: 'feature', name: 'Feature', color: 'green' },
  { id: 'documentation', name: 'Documentation', color: 'blue' },
  { id: 'refactor', name: 'Refactor', color: 'yellow' },
  { id: 'performance', name: 'Performance', color: 'orange' },
  { id: 'design', name: 'Design', color: 'pink' },
  { id: 'security', name: 'Security', color: 'gray' },
  { id: 'accessibility', name: 'Accessibility', color: 'indigo' },
  { id: 'testing', name: 'Testing', color: 'teal' },
  { id: 'internationalization', name: 'Internationalization', color: 'cyan' },
];

export const RAW_CYCLES = [
  {
    id: '23',
    number: 23,
    name: 'Cycle 23',
    teamId: 'CORE',
    status: 'planned',
    startDate: '2026-08-17',
    endDate: '2026-08-30',
    capacity: 0,
  },
  {
    id: '22',
    number: 22,
    name: 'Cycle 22',
    teamId: 'CORE',
    status: 'upcoming',
    startDate: '2026-08-03',
    endDate: '2026-08-16',
    capacity: 45,
  },
  {
    id: '21',
    number: 21,
    name: 'Cycle 21',
    teamId: 'CORE',
    status: 'current',
    startDate: '2026-07-20',
    endDate: '2026-08-02',
    capacity: 85,
  },
  {
    id: '20',
    number: 20,
    name: 'Cycle 20',
    teamId: 'CORE',
    status: 'completed',
    startDate: '2026-07-06',
    endDate: '2026-07-19',
    capacity: 90,
    successRate: 85,
  },
  {
    id: '19',
    number: 19,
    name: 'Cycle 19',
    teamId: 'CORE',
    status: 'completed',
    startDate: '2026-06-22',
    endDate: '2026-07-05',
    capacity: 95,
    successRate: 90,
  },
];

export const RAW_INITIATIVES = [
  {
    id: 'component-platform',
    name: 'Q3 — Ship the component platform',
    description: 'Deliver the full core component suite with stable APIs and docs.',
    icon: '🧱',
    status: 'active',
    priorityId: 'no-priority',
    ownerId: 'ln',
    target: 'Q3 2026',
    healthId: 'on-track',
    projectIds: ['1', '2', '3', '7', '13', '19'],
  },
  {
    id: 'quality-accessibility',
    name: 'Q3 — Raise quality and accessibility',
    description: 'WCAG AA across the library, visual regression coverage and audits.',
    icon: '♿',
    status: 'active',
    priorityId: 'high',
    ownerId: 'emma',
    target: 'Q3 2026',
    healthId: 'at-risk',
    projectIds: ['4', '10', '16', '22'],
  },
  {
    id: 'design-system-adoption',
    name: 'Q4 — Grow design system adoption',
    description: 'Templates, starter kits and integrations that drive adoption.',
    icon: '🌱',
    status: 'active',
    priorityId: 'medium',
    ownerId: 'sophia',
    target: 'Q4 2026',
    healthId: 'no-update',
    projectIds: ['5', '11', '17', '23'],
  },
  {
    id: 'performance-lab',
    name: 'Q3 — Cut bundle size in half',
    description: 'Tree-shakeable exports, lazy primitives and a leaner runtime.',
    icon: '⚡',
    status: 'active',
    priorityId: 'urgent',
    ownerId: 'alex',
    target: 'Q3 2026',
    healthId: 'on-track',
    projectIds: ['6', '12', '18'],
  },
  {
    id: 'docs-refresh',
    name: 'Q3 — Documentation refresh',
    description: 'Interactive playground, copyable recipes and search indexing.',
    icon: '📚',
    status: 'active',
    priorityId: 'no-priority',
    ownerId: 'lucas',
    target: 'Q3 2026',
    healthId: 'no-update',
    projectIds: ['8', '14', '20'],
  },
];

export const RAW_DOCUMENT_FOLDERS = [
  {
    id: 'team-documents',
    name: 'Team documents',
    icon: '📁',
    teamId: 'CORE',
    documents: [
      {
        id: 'doc-1',
        name: 'LNDev UI Team Calendar',
        icon: '📆',
        creatorId: 'ln',
        createdAt: '2026-07-08',
        updatedAt: '2026-07-30',
        pinned: true,
      },
    ],
  },
  {
    id: 'design-tokens-v2',
    name: 'Design Tokens v2',
    icon: '🎨',
    teamId: 'CORE',
    documents: [
      {
        id: 'doc-2',
        name: 'PRD - Design Tokens v2 (OKLCH migration)',
        icon: '📄',
        creatorId: 'mason',
        createdAt: '2026-06-15',
        updatedAt: '2026-07-22',
      },
      {
        id: 'doc-3',
        name: 'Spec: Token naming conventions',
        icon: '📐',
        creatorId: 'alex',
        createdAt: '2026-06-18',
        updatedAt: '2026-06-30',
      },
    ],
  },
];

export const RAW_SAVED_VIEWS = [
  {
    id: 'blocked-3-days',
    teamId: 'CORE',
    name: '+ 3 days blocked issues',
    description: 'Issues that are Blocked or Paused for more than 3 days',
    icon: '🧊',
    type: 'issue',
    ownerId: 'ln',
    filter: { statusIds: ['blocked', 'paused'] },
  },
  {
    id: 'in-progress-recent',
    teamId: 'CORE',
    name: '+1 day in progress',
    description: 'Issues that started in the last day and are currently in progress',
    icon: '⏱️',
    type: 'issue',
    ownerId: 'ln',
    filter: { statusIds: ['in-progress'] },
  },
  {
    id: 'all-active-projects',
    name: 'All projects',
    description: 'Projects that are currently in progress',
    icon: '📦',
    type: 'project',
    ownerId: 'ln',
    filter: { statusCategories: ['started'] },
  },
];
