name: Deploy Backend to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          timeout: 300s
          script: |
            bash /opt/classpro/be/deploy.sh
